# Generated by Django 4.0.3 on 2022-03-31 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=25.0, max_digits=15)),
                ('description', models.TextField()),
                ('animal', models.CharField(choices=[('cat', 'Cat'), ('dog', 'Dog')], default='dog', max_length=10)),
            ],
        ),
    ]
